### PR TITLE
Add canonical import path

### PR DESCRIPTION
**Pull request by bouk**
Vanity

### CODE REVIEW

**Comment by chapsuk** [comment]
Hi @bouk !
This changes broken vendoring 🐒 by dep 😢 

using `import "bou.ke/monkey"`

```
≻ dep ensure
panic: version queue is empty, should not happen

goroutine 1 [running]:
github.com/golang/dep/gps.(*solver).findValidVersion(0xc4202fc5a0, 0xc4205a5220, 0xc420547b00, 0x1, 0x1, 0x0, 0xc420547b00)
	/private/tmp/dep-20180127-38430-r7nlwc/src/github.com/golang/dep/gps/solver.go:927 +0x53f
github.com/golang/dep/gps.(*solver).createVersionQueue(0xc4202fc5a0, 0xc4208dcd41, 0x14, 0x0, 0x0, 0xc420547b00, 0x1, 0x1, 0x0, 0x0, ...)
	/private/tmp/dep-20180127-38430-r7nlwc/src/github.com/golang/dep/gps/solver.go:914 +0x955
github.com/golang/dep/gps.(*solver).solve(0xc4202fc5a0, 0x17e7e40, 0xc420014078, 0xc4200c33f8, 0x40, 0x40)
	/private/tmp/dep-20180127-38430-r7nlwc/src/github.com/golang/dep/gps/solver.go:517 +0x5b0
github.com/golang/dep/gps.(*solver).Solve(0xc4202fc5a0, 0x17e7e40, 0xc420014078, 0xc42024c9e0, 0x20, 0x20, 0xc4202de200)
	/private/tmp/dep-20180127-38430-r7nlwc/src/github.com/golang/dep/gps/solver.go:457 +0xe4
main.(*ensureCommand).runDefault(0xc420153ee6, 0xc420051080, 0xc42000a080, 0x0, 0x0, 0xc4200510e0, 0x17eb320, 0xc4200517a0, 0xc420016084, 0x3a, ...)
	/private/tmp/dep-20180127-38430-r7nlwc/src/github.com/golang/dep/cmd/dep/ensure.go:302 +0x168
main.(*ensureCommand).Run(0xc420153ee6, 0xc420051080, 0xc42000a080, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/dep-20180127-38430-r7nlwc/src/github.com/golang/dep/cmd/dep/ensure.go:220 +0x8f4
main.(*Config).Run(0xc420050f60, 0xc420050f60)
	/private/tmp/dep-20180127-38430-r7nlwc/src/github.com/golang/dep/cmd/dep/main.go:210 +0x11cb
main.main()
	/private/tmp/dep-20180127-38430-r7nlwc/src/github.com/golang/dep/cmd/dep/main.go:52 +0x1fc
```

using `import github.com/bouk/monkey/`

```
Solving failure: No versions of github.com/bouk/monkey met constraints:
	master: Could not introduce github.com/bouk/monkey@master, as its subpackage github.com/bouk/monkey does not contain usable Go code (*pkgtree.NonCanonicalImportRoot).. (Package is required by (root).)
```

additional info:
```
≻ dep version
dep:
 version     : v0.4.1
 build date  : 2018-01-27
 git hash    : 37d9ea0
 go version  : go1.9.3
 go compiler : gc
 platform    : darwin/amd64
```

Can you please publish release tag from https://github.com/bouk/monkey/commit/5df1f207ff77e025801505ae4d903133a0b4353f ?

**Comment by bouk** [comment]
OK I tagged it as v1.0.0. You can also just change the import to `bou.ke/monkey`

**Comment by chapsuk** [comment]
Thanks! 
I'm got `panic` on `dep ensure` when change import to `bou.ke/monkey`, not sure why

**Comment by chapsuk** [comment]
Sorry for my misunderstand, panic from [another dependency](https://github.com/golang/dep/issues/1799).

After releases works great for me:

```go
import  "bou.ke/monkey"
```
```
(51)  ? attempt bou.ke/monkey with 1 pkgs; 3 versions to try
(53)      try bou.ke/monkey@v1.0.1
(53)  ✓ select bou.ke/monkey@v1.0.1 w/1 pkgs
```

```go 
import "github.com/bouk/monkey"
```

```
(52)  ? attempt github.com/bouk/monkey with 1 pkgs; 3 versions to try
(55)      try github.com/bouk/monkey@v1.0.1
(56)  ✗   github.com/bouk/monkey at v1.0.1 has problem subpkg(s):
(56)    	github.com/bouk/monkey has err (*pkgtree.NonCanonicalImportRoot); required by (root).
(55)      try github.com/bouk/monkey@v1.0.0
(55)  ✓ select github.com/bouk/monkey@v1.0.0 w/1 pkgs
```

Thanks very much!

**Pull request merged**
