### PR TITLE
Question about license

### PR DESCRIPTION
**Pull request by artiomgiza**
Hi, Bouke!

As you surely know, current license of your wonderful project looks like:
```
Copyright Bouke van der Bijl
I do not give anyone permissions to use this tool for any purpose. Don't use it.
```
This certainly unique :)

Actually, this license don't give a permissions to use the project, but people actually want use it pretty much. 
Could you might be consider to update the license to something more common, as MIT or BSD ([link](https://help.github.com/articles/licensing-a-repository))?

Thank you in advance!
Artiom Giza

### CODE REVIEW

**Comment by bouk** [comment]
This license is not an accident. This is a satirical project that shouldn’t be used

**Comment by eyalpost** [comment]
@bouk Can you please reconsider?
Although this might not be safe for production use, It is still very useful in tests and we currently can't use it because of the license issue. Even a license for non-production use will be better than nothing

**Comment by adammw** [comment]
Ditto @bouk. We really need this to improve our test coverage, please put it under a license where we can actually use what you're already sharing on GitHub.

**Comment by bouk** [comment]
No

**Pull request closed without merging**
